export default function ($translateProvider) {
  $translateProvider.translations('zh', {
    'BACK'                 : '返回',
    'DELETE'               : '删除',
    'CREATE'               : '添加',
    'EDIT'                 : '编辑',
    'EXPORT'               : '导出',
    'ADD_FILTER'           : '添加过滤',
    'SEE_RELATED'          : '查看所有相关的{{ entityName }}',
    'LIST'                 : '列表',
    'SAVE'                 : '保存',
    'N_SELECTED'           : '已选择 {{ length }} 项',
    'ARE_YOU_SURE'         : '确定?',
    'YES'                  : '是的',
    'NO'                   : '不',
    'FILTER_VALUES'        : '搜索',
    'CLOSE'                : '关闭',
    'CLEAR'                : '清除',
    'CURRENT'              : '当前',
    'REMOVE'               : '移除',
    'ADD_NEW'              : '新增 {{ name }}',
    'BROWSE'               : '浏览',
    'N_COMPLETE'           : '已完成{{ progress }}%',
    'CREATE_NEW'           : '新增',
    'SUBMIT'               : '提交',
    'SAVE_CHANGES'         : '保存更改',
    'BATCH_DELETE_SUCCESS' : '批量删除成功',
    'DELETE_SUCCESS'       : '删除成功',
    'ERROR_MESSAGE'        : '欧肉, 发生了一个错误!<br/> (错误代码: {{ status }})',
    'INVALID_FORM'         : '无效的表单',
    'CREATION_SUCCESS'     : '创建成功',
    'EDITION_SUCCESS'      : '已保存更改',
    'ACTIONS'              : '操作',
    'PAGINATION'           : '当前为<strong>{{ begin }}</strong> - <strong>{{ end }}</strong>条, 共 <strong>{{ total }}</strong>条记录',
    'NO_PAGINATION'        : '没有记录',
    'PREVIOUS'             : '« 上一页',
    'NEXT'                 : '下一页 »',
    'DETAIL'               : '详情',
    'SHOW'                 : '详情',
    'REPLY'                : '回复',
    'STATE_CHANGE_ERROR'   : '{{ message }}',
    'STATE_FORBIDDEN_ERROR': '没有权限访问: {{ message }}',
    'NOT_FOUND'            : '未找到',
    'NOT_FOUND_DETAILS'    : '未找到该内容, 请稍后再试!'
  });
  $translateProvider.preferredLanguage('zh');
  $translateProvider.useSanitizeValueStrategy(null);
}